language: java
jdk:
  - oraclejdk8
env:
  global:
  - secure: ""
  - secure: ""
addons:

before_install:

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN
